### ISSUE TITLE
Network library not included or not supported

### ISSUE THREAD

**Issue by MULAWI** [Edistechlab/DIY-Heimautomation-Buch#2]
Hallo Edi

habe das ganze so übernommen wie im Video beschrieben, habe es mal compiliert aber die Fehlermeldung kommt immer wieder obwohl ich alle librarys mit der genauen Version runtergeladen habe. Kannst du mir mitteilen, was ich falsch gemacht habe? Ausserdem kann ich unter Boards die ESP32 und 8266 nicht finden. Besten Dank! LG Murat

Arduino: 1.8.13 (Mac OS X), Board: "Arduino Uno"
In file included from /Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino:27:0:
/Users/muratcobanoglu/Documents/Arduino/libraries/ArduinoOTA/src/ArduinoOTA.h:133:2: warning: #warning "Network library not included or not supported" [-Wcpp]
 #warning "Network library not included or not supported"
  ^~~~~~~
BME280_I2C_OTA_MQTT:51:1: error: 'WiFiClient' does not name a type; did you mean 'DNSClient'?
 WiFiClient espClient;
 ^~~~~~~~~~
 DNSClient
BME280_I2C_OTA_MQTT:52:21: error: 'espClient' was not declared in this scope
 PubSubClient client(espClient);
                     ^~~~~~~~~
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino:52:21: note: suggested alternative: 'DNSClient'
 PubSubClient client(espClient);
                     ^~~~~~~~~
                     DNSClient
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino: In function 'void setup()':
BME280_I2C_OTA_MQTT:60:4: error: 'ArduinoOTA' was not declared in this scope
    ArduinoOTA.setHostname(ESPHostname);
    ^~~~~~~~~~
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino:60:4: note: suggested alternative: 'Arduino_h'
    ArduinoOTA.setHostname(ESPHostname);
    ^~~~~~~~~~
    Arduino_h
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino: In function 'void loop()':
BME280_I2C_OTA_MQTT:77:3: error: 'ArduinoOTA' was not declared in this scope
   ArduinoOTA.handle();
   ^~~~~~~~~~
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino:77:3: note: suggested alternative: 'Arduino_h'
   ArduinoOTA.handle();
   ^~~~~~~~~~
   Arduino_h
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino: In function 'void setup_wifi()':
BME280_I2C_OTA_MQTT:118:3: error: 'WiFi' was not declared in this scope
   WiFi.begin(wifi_ssid, wifi_password);
   ^~~~
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino:118:3: note: suggested alternative: 'Wire'
   WiFi.begin(wifi_ssid, wifi_password);
   ^~~~
   Wire
BME280_I2C_OTA_MQTT:119:27: error: 'WL_CONNECTED' was not declared in this scope
   while (WiFi.status() != WL_CONNECTED) {
                           ^~~~~~~~~~~~
/Users/muratcobanoglu/Documents/Arduino/BME280_I2C_OTA_MQTT/BME280_I2C_OTA_MQTT.ino:119:27: note: suggested alternative: 'MQTT_CONNECTED'
   while (WiFi.status() != WL_CONNECTED) {
                           ^~~~~~~~~~~~
                           MQTT_CONNECTED
exit status 1
'WiFiClient' does not name a type; did you mean 'DNSClient'?

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by Edistechlab** [comment]
Hallo Murat,
Ich gehe ganz stark davon aus, dass du die ESP Boards noch nicht in der Arduino IDE hinzugefügt hast.

Wie man die beiden ESP Boards einbindet zeige ich hier in diesem Video: https://youtu.be/I_hruIWEDeg

Vor dem Kompilieren muss dann natürlich das richtige Board ausgewählt sein, NodeMCU, ESP8266 oder der ESP32 
Je nachdem für welches Board du den Code generieren möchtest.


Ich hoffe das hilft und liebe Grüsse
Edi


Die beiden Links für ESP8266 und ESP32 Json files:
► http://arduino.esp8266.com/stable/package_esp8266com_index.json
► https://dl.espressif.com/dl/package_esp32_index.json <https://dl.espressif.com/dl/package_esp32_index.json>

**Comment by MULAWI** [comment]
Besten Dank Edi
kenne dein Video bereits und habe alles nach dem eingerichtet, auch den Code in Arduino IDE reinkopiert... mit dem ESP8266 funktioniert alles und es compliliert jedoch beim ESP32 funktioniert es einfach nicht, egal welches Board ich nehme.(ESP32 Dev Module)

Nochmals besten Dank für deine Bemühungen!

Gruss Murat

`Arduino: 1.8.13 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 115200, None"

Traceback (most recent call last):
  File "esptool.py", line 57, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports.py", line 29, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_posix.py", line 31, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "serial/tools/list_ports_osx.py", line 32, in <module>
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found
Failed to execute script esptool
Multiple libraries were found for "ArduinoOTA.h"
 Used: /Users/muratcobanoglu/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/ArduinoOTA
 Not used: /Users/muratcobanoglu/Documents/Arduino/libraries/ArduinoOTA
Multiple libraries were found for "WiFi.h"
 Used: /Users/muratcobanoglu/Library/Arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
exit status 255
/Applications/Arduino.app/Contents/Java/arduino-builder returned 255
Error compiling for board ESP32 Dev Module.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by Edistechlab** [comment]
Hallo Murat,

Eines ist mir noch aufgefallen was du überprüfen könntest.

Wenn man den ESP32 verwendet, dann muss der //#include <WiFi.h> Aus Kommentiert
Werden.

Ich hoffe das ist jetzt der Fehler.


https://github.com/Edistechlab/DIY-Heimautomation-Buch/blob/master/Sensoren/Temperatur%20Luftfeuchte%20Sensoren/BME280_I2C_MQTT_OTA_V1.0/BME280_I2C_MQTT_OTA_V1.0.ino





Liebe Grüsse Edi

**Comment by MULAWI** [comment]
Das hatte ich bereits getan, beim 8266 habe ich es kommentiert und beim ESP32 auskommentiert. Aber klappt nicht, weder in Arduino IDE noch unter platformIO.

Danke trotzdem für deine Bemühungen.
